name: Benchmarks

on: [workflow_dispatch]

jobs:
  bench:
    name: Bench Targets
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@nightly

    - name: Check
      run: cargo check

    - name: Test
      run: |
        cargo test
        cd devel
        cargo test

    - name: Run Benchmarks
      run: |
        cd devel
        cargo bench

  bench-macos:
    name: Bench Targets
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@nightly

    - name: Check
      run: cargo check

    - name: Test
      run: |
        cargo test
        cd devel
        cargo test

    # Run a single benchmark for quick evaluation our code works.
    - name: Run Benchmarks
      run: |
        cd devel
        cargo bench --bench mul_algos mul64/simple::mul64_v3

    - name: Print Simple Benchmark
      run: |
        cd devel
        cargo run --features print-benches --bin print-benches

    - name: Run Benchmarks
      run: |
        cd devel
        cargo bench

    - name: Print Benchmarks
      run: |
        cd devel
        cargo run --features print-benches --bin print-benches
