name: Benchmarks

on: [workflow_dispatch]

jobs:
  bench:
    name: Bench Targets
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        target: [x86_64, aarch64]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@nightly

    - name: Check
      run: cargo check

    - name: Test
      run: |
        cargo test
        cd devel
        cargo test

    - name: Run Benchmarks
      run: |
        cd devel
        cargo bench

  bench-macos:
    name: Bench Targets
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@nightly

    - name: Check
      run: cargo check

    - name: Test
      run: |
        cargo test
        cd devel
        cargo test

    - name: Run Benchmarks
      run: |
        cd devel
        cargo bench
