name: Cross

on: [workflow_dispatch]

jobs:
  cross:
    name: Cross
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # NOTE: mips was dropped from tier 2 support, so remove this
        # when we go to higher versions. This is just to test BE support.
        target: [mips64-unknown-linux-gnuabi64, aarch64-unknown-linux-gnu]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@nightly

    - name: Install Cross
      run: |
        cargo install cross@0.2.5
        rustup toolchain add 1.59.0

    - name: Run Check
      run: |
        cross +1.59.0 check --target ${{matrix.target}}

    - name: Run Test
      run: |
        cross +1.59.0 test --target ${{matrix.target}}
